### ISSUE TITLE
change urls

### ISSUE THREAD

**Issue by ffaerber** [buzzn/display-app#54]
change to urls for staging develop and production

**Comment by ffaerber** [comment]
@dottorer can you please add the display app urls to cloudflare.
display.buzzn.io => d1jjux7bphmdfj.cloudfront.net
develop-display.buzzn.io =>  d1smtnxi068s9t.cloudfront.net
staging-display.buzzn.io => ds9skivlb0sm.cloudfront.net

**Comment by dottorer** [comment]
@ffaerber Done. give it a minute to sink in....
