### ISSUE TITLE
Use Bubbles v2 module

### ISSUE THREAD

**Issue by scsirdx** [buzzn/display-app#55]
Split bubbles-module into small parts, so it will be more customisable (show/hide different parts, change colours, etc...).
Investigate performance for the d3math + react svg. If it's ok, then stick with this solution. Later d3 can be switched to matter.js for better performance.

**Comment by scsirdx** [comment]
This is a low priority ticket.

**Comment by dottorer** [comment]
@scsirdx @ffaerber 
Requested mockups from Danusch for bubbles with:
A. lots of production, little consumption by many consumer bubbles.
B. lots of production, lots of consumption in varying sizes.
C. little production, lots of consumption.
This should give us a better idea of how the physics engine needs to function, etc.

**Comment by dottorer** [comment]
Additionally we will mockup how images of the power taker will be shown in bubbles and how certain bubbles (elevator, kitchrn, lighting) could be visually featured.

**Comment by scsirdx** [comment]
We also need mockups for the 3 different apps with different information displayed (tooltips, additional info, etc...)

**Comment by dottorer** [comment]
Mockups v1 in: https://app.zeplin.io/project.html#pid=58c6beb5b3756ccd9517aa88&dashboard

**Comment by ChriWiChris** [comment]
done in #56
