### ISSUE TITLE
Display App shows wrong values for 'Sulz' local pool

### ISSUE THREAD

**Issue by dottorer** [buzzn/display-app#62]
Based on a comparison with the discovergy values, we seem to show double the values for PV and BHKW:

![image](https://user-images.githubusercontent.com/14217285/26921128-60b5e912-4c3b-11e7-92f8-1503bc64cf01.png)

Also, the total feed in is off in consequence.

Finally the production / consumption line chart does show only one line.

**Comment by mkristian** [comment]
@dottorer @scsirdx develop-display.buzzn.io is showing both charts. staging-display.buzzn.io only one chart. not sure whether we have the same code running on both, i.e. both using the same backend: staging-core.buzzn.io.

**Comment by mkristian** [comment]
@scsirdx if I can help with those double values - let me know, i.e. would look at them on the server side and also see the discovergy raw response, etc

**Comment by scsirdx** [comment]
It was a backend problem. Will be fixed on next staging deploy.

**Comment by dottorer** [comment]
Fixed by buzzn/buzzn#1061.
