### ISSUE TITLE
Fix energy calculation

### ISSUE THREAD

**Issue by scsirdx** [buzzn/display-app#66]
We need to use the correct formula to calculate energy up to a specific point in time for a day.

**Comment by dottorer** [comment]
Correct formula to use: Sum all values in an hour interval and build mean value. Then add up all hourly kWh results for the day up to this point.


hr1 in kWh = (val1 in kW + val2 + val3 + val4) / vals_in_hour        +
hr2 = (val1 + val2 + val3 + val4) / vals_in_hour        +
…
current_hr = (val1 + val2 ) / vals_in_hour                  =
total_energy_up_to_moment in kWh

**Comment by dottorer** [comment]
Peer reviewed with @drthth ; Discovergy uses same approach as do others.

**Comment by mkristian** [comment]
@dottorer question: `vals_in_hour` is always 4 in the examples above ? or is the last one 
`current_hr = (val1 + val2 ) / 2 = total_energy_up_to_moment in kWh` ?

**Comment by dottorer** [comment]
@mkristian let's say the current hour is not completed yet and it is 17:35. We have only 2 values of 15-min increments, so we need to build the mean of the 2 values. For all full hour we can use 4 quarter hour values.

**Comment by scsirdx** [comment]
@mkristian ```chunk(data, 4).reduce((sh, h) => (h.reduce((sv, v) => (sv + v.value), 0) / h.length) + sh, 0);```
`chunk` is a function that
```
 chunk([1, 2, 3, 4, 5, 6], 4)   -> [[1, 2, 3, 4], [5, 6]]
```

**Comment by mkristian** [comment]
I got it now. for `vals_in_hour` look like a variable but it was a description of a number. thanks
