### ISSUE TITLE
Investigate app crash

### ISSUE THREAD

**Issue by scsirdx** [buzzn/display-app#68]
On some computers (Ralf) browser tab freezes/crashes after some time.
Need more testing on different machines.

**Comment by dottorer** [comment]
![image](https://user-images.githubusercontent.com/14217285/29108705-6c8aa18a-7ce0-11e7-9b4b-95b6c02db96f.png)

@scsirdx I noticed that if I leave a tab open in Chrome in admin app (and a page with bubbles on it), when I come back to it, it no longer works. It does not load anything and in the bottom bar it says "waiting for  staging-core.buzzn.io". Could it be that some form of timeout occurs?#

Also, I am running privacy badger, and adblock plus, an https anywhere. Maybe that factors in.

**Comment by dottorer** [comment]
Interesting, waiting for long enough has finally brought up the page. What could take so long that Chrome takes it for a page crash?

**Comment by scsirdx** [comment]
@dottorer Did you run that tab in background?

**Comment by dottorer** [comment]
@scsirdx Yes, in this particular case I open the app, then move to another tab or leave the computer. When I get the Chrome tab is unresponsive.

**Comment by dottorer** [comment]
@scsirdx I know this has been a long standing but I have not been able to trigger this issue again lately. The Display app runs pretty reliably. The Admin app has not been accessible for a while but recent tests showed it running ok as well. 

Should we close this out and create a new one if it resurfaces?
