### ISSUE TITLE
PROD: Display app for Mehrgenerationenplatz show now power consumption

### ISSUE THREAD

**Issue by dottorer** [buzzn/display-app#69]
![image](https://user-images.githubusercontent.com/14217285/29161283-efbb01b4-7db5-11e7-96cd-596cffebed50.png)

**Comment by dottorer** [comment]
@scsirdx production issue. Likely backend causes but let's start investigating.

Also note the confusing  '143,100' value for total production. We should always only have 2 post-decimal digits..

**Comment by dottorer** [comment]
Most groups show consumption values (like 'Wagnis4'). Others do not (e.g. 'Wogeno Power'). Could this something to do with optimized groups?

**Comment by dottorer** [comment]
Seems like this bug is fixed in https://display.buzzn.io/mehrgenerationenplatz-forstenried 

@mkristian Did you resolve this or magic?

**Comment by mkristian** [comment]
I would call it magic. I totally lost track of what is deployed on staging or production.

**Comment by dottorer** [comment]
Closing as Cannot Reproduce
