### ISSUE TITLE
Expose display app content in iframe for portal

### ISSUE THREAD

**Issue by dottorer** [buzzn/display-app#70]
Our customer IsarWatt is working on a portal to integrate buzzn energy display data. Prototype here: https://p1.his.argserver.de/pep-demo.html

We should spike the effort to fill in a slot with our data.

For this we need to start wit ha wireframe mockup of what we would expose.

**Comment by dottorer** [comment]
I have been playing around with how our display app content could appear in the iframe based portal.

While we could chop up the content, it seems that if we just sized the whole display app, it could fit fine. Note that this is something people stand in front of closely to read the other content.

![image](https://user-images.githubusercontent.com/14217285/30559756-fe9905e0-9cb5-11e7-971d-81109f16ff6a.png)

[iframe_display.pptx](https://github.com/buzzn/display-app/files/1311886/iframe_display.pptx)

@evaklopp Thoughts?
@scsirdx Could we just scale down the whole app and expose in iframe code ("cut this snippet to include in your page")? Could it work for other sites/blogs/etc then too?

**Comment by scsirdx** [comment]
@dottorer It was already done, you can embed the whole app and it will scale to any size:
wise-screw.surge.sh

**Comment by dottorer** [comment]
To my understanding Hrndrik tried embedding the whole thing but it did not scale. In fact the prototype shows this. Maybe we can give him the code snippet iframe fixed to his size?

**Comment by dottorer** [comment]
This is nicely resolved by @scsirdx . Thanks!
